apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-pass
type: Opaque
data:
  password: WVVJaWRoYjY2Nw== # Base64 encoded value of "YUIidhb667"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass
type: Opaque
data:
  username: a29kZWtsb3VkX3NhbQ== # Base64 encoded value of "kodekloud_sam"
  password: QjRabkdIQTdZQQ== # Base64 encoded value of "B4zNgHA7Ya"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-url
type: Opaque
data:
  database: a29kZWtsb3VkX2RiMg== # Base64 encoded value of "kodekloud_db2"