apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ReplicationController","metadata":{"annotations":{},"name":"nginx-replicationcontroller","namespace":"default"},"spec":{"replicas":3,"selector":{"app":"nginx_app","type":"front-end"},"template":{"metadata":{"labels":{"app":"nginx_app","type":"front-end"},"name":"nginx"},"spec":{"containers":[{"image":"nginx:latest","name":"nginx-container","ports":[{"containerPort":80}]}]}}}}
  generation: 1
  labels:
    app: nginx_app
    type: front-end
  name: nginx-replicationcontroller
  namespace: default
  resourceVersion: "2380"
  replicas: 3
  selector:
    app: nginx_app
    type: front-end
  template:
    metadata:
      creationTimestamp: null
      labels:
      labels:
        app: nginx_app
        type: front-end
      name: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx-container
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
