apiVersion : v1
kind : PersistentVolume
metadata : 
  name : pv-xfusion
spec :
  storageClassName : manual
  capacity : 
    storage : 4Gi
  accessModes :
    - ReadWriteOnce
  hostPath :
    path : /mnt/data
    type : DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: pvc-xfusion
    namespace: default
---
apiVersion : v1
kind : PersistentVolumeClaim
metadata : 
  name : pvc-xfusion
spec :
  storageClassName : manual
  accessModes :
    - ReadWriteOnce
  resources :
    requests :
      storage : 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-xfusion
spec:
  containers:
  - name: container-xfusion
    image: nginx:latest
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: xfusion-storage
  volumes:
  - name: xfusion-storage
    persistentVolumeClaim:
      claimName: pvc-xfusion
---
# apiVersion : v1
# kind : Service
# metadata : 
#   name : web-xfusion
# spec :
#   type : NodePort
#   selector :
#     app : xfusion
#   ports :
#     - protocol : TCP
#       port : 80
#       targetPort : 80
#       nodePort : 30008