# Create a deployment named lemp-wp.
# Create two containers under it. First container must be 
# nginx-php-container using image webdevops/php-nginx:alpine-3-php7
#  and second container must be mysql-container from image mysql:5.6. Mount 
#  php-config configmap in nginx container at /opt/docker/etc/php/php.ini location.
# 5) Add some environment variables for both containers:
# MYSQL_ROOT_PASSWORD, MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD
# and MYSQL_HOST. Take their values from the secrets you created. 
# Please make sure to use env field (do not use envFrom) to define
# the name-value pair of environment variables.
# 6) Create a node port type service lemp-service to expose the
#  web application, nodePort must be 30008.
# 7) Create a service for mysql named mysql-service and its 
# port must be 3306.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemp-wp
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: lemp-wp
  template:
    metadata:
      labels:
        app: lemp-wp
    spec:
      containers:
      - name: nginx-php-container
        image: webdevops/php-nginx:alpine-3-php7
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: wordpress-persistent-storage
        - mountPath: /opt/docker/etc/php/php.ini
          subPath: php.ini
          name: php-config
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-host
              key: host
      - name: mysql-container
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-host
              key: host
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
      - name: wordpress-persistent-storage
        emptyDir: {}
      - name: php-config
        configMap:
          name: php-config
      - name: mysql-persistent-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lemp-service
  labels:
    app: lemp-wp
spec:
  type: NodePort
  selector:
    app: lemp-wp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008 
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: lemp-wp
  ports:  
  - protocol: TCP
    port: 3306
    targetPort: 3306
