# 1) Create a config map php-config for php.ini with variables_order
# = "EGPCS" data.
# 2) Create a deployment named lamp-wp.
# 3) Create two containers under it. 
# First container must be httpd-php-container using image 
# webdevops/php-apache:alpine-3-php7 and second container must be
# mysql-container from image mysql:5.6. Mount php-config configmap
# in httpd container
# at /opt/docker/etc/php/php.ini location.
# 4) Create kubernetes generic secrets for mysql related values 
# like myql root password, mysql user, mysql password, mysql host and 
# mysql database. 
# Set any values of your choice.
# 5) Add some environment variables for both containers:
# a) MYSQL_ROOT_PASSWORD, MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD a
# nd MYSQL_HOST. Take their values from the secrets you created. Please make
#  sure to use env field (do not use envFrom) to define the name-value pair
#   of environment variables.
# 6) Create a node port type service lamp-service to expose the 
# web application, nodePort must be 30008.
# 7) Create a service for mysql named mysql-service and its port
#  must be 3306.
# 8) We already have /tmp/index.php file on jump_host server.
# a) Copy this file into httpd container under Apache document 
# root i.e /app and replace the dummy values for mysql related
#  variables with the environmen
#  t variables you have set for mysql related parameters.
#   Please make sure you do not hard code the mysql related 
#   details in this file, you must use the environment variables
#    to fetch those values.
# b) You must be able to access this index.php on node port 
# 30008 at the end, please note that you should see Connected 
# successfully message while accessing this page.
apiVersion: apps/v1
kind : ConfigMap
metadata : 
  name : php-config
data :
  php.ini : |
    variables_order = "EGPCS"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp-wp
  template:
    metadata:
      labels:
        app: lamp-wp
    spec:
      containers:
      - name: httpd-php-container
        image: webdevops/php-apache:alpine-3-php7
        volumeMounts:
        - name: php-config
          mountPath: /opt/docker/etc/php/php.ini
          subPath: php.ini
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: host
      - name: mysql-container
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
      volumes:
      - name: php-config
        configMap:
          name: php-config
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  root-password: bXlyb290cGFzc3dvcmQ=
  database: bXlkYXRhYmFzZQ==
  user: bXl1c2Vy
  password: bXlwYXNzd29yZA==
  host: bXlzcWwtc2VydmljZQ==
---
apiVersion: v1
kind: Service
metadata:
  name: lamp-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30008
  selector:
    app: lamp-wp
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: lamp-wp
---
