apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"ReplicaSet","metadata":{"annotations":{},"labels":{"app":"nginx_app","type":"front-end"},"name":"nginx-replicaset","namespace":"default"},"spec":{"replicas":4,"selector":{"matchLabels":{"app":"nginx_app","type":"front-end"}},"template":{"metadata":{"labels":{"app":"nginx_app","type":"front-end"}},"spec":{"containers":[{"image":"nginx:latest","name":"nginx-container","ports":[{"containerPort":80}]}]}}}}
  generation: 1
  labels:
    app: nginx_app
    type: front-end
  name: nginx-replicaset
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx_app
      type: front-end
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx_app
        type: front-end
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx-container
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  fullyLabeledReplicas: 4
  observedGeneration: 1
  replicas: 4
