# It should have one container called httpd, use httpd:2.4.28 image and 3 replicas.
#  The deployment should use RollingUpdate strategy with maxSurge=1,
#   and maxUnavailable=2. Also create a NodePort type service named httpd-servic
#   e and expose the deployment on nodePort: 30008.


# Now upgrade the deployment to version httpd:2.4.43 using a rolling update.


# Finally, once all pods are updated undo the recent update and roll back to 
# the previous/original version.
apiVersion: v1
kind: Namespace
metadata:
  name: devops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      containers:
      - name: httpd-container
        image: httpd:2.4.28
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: devops
spec:
  type: NodePort  
  selector:
    app: httpd-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008