apiVersion: v1
data:
  maxmemory: 2mb
  maxmemory-policy: allkeys-lru
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"maxmemory":"2mb","maxmemory-policy":"allkeys-lru"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"redis-config","namespace":"default"}}
  creationTimestamp: "2025-03-07T12:34:35Z"
  name: redis-config
  namespace: default
  resourceVersion: "2088"
  uid: 46c0ff76-51f2-4a9a-a86a-7cf9d2d3bb92