apiVersion : v1
kind : Service
metadata :
  name : iron-db-service-datacenter
  namespace : iron-namespace-datacenter
spec :  
  selector :
    db : mariadb
  ports :
    - protocol : TCP
      port : 3306
      targetPort : 3306
  type : ClusterIP
---
apiVersion : v1
kind : Service
metadata :
  name : iron-gallery-service-datacenter
  namespace : iron-namespace-datacenter
spec :
  selector :
    run : iron-gallery
  ports :
    - protocol : TCP
      port : 80
      targetPort : 80
      nodePort : 32678
  type : NodePort