apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-xfusion
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/itadmin
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: pvc-xfusion
    namespace: default