apiVersion: v1
kind: Pod
metadata:
  name: pod-xfusion
spec:
  containers:
  - name: container-xfusion
    image: nginx:latest
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: xfusion-storage
  volumes:
  - name: xfusion-storage
    persistentVolumeClaim:
      claimName: pvc-xfusion