apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"python-service-xfusion","namespace":"default"},"spec":{"ports":[{"nodePort":32345,"port":8080}],"selector":{"app":"python_app"},"type":"NodePort"}}
  creationTimestamp: "2025-03-15T10:04:49Z"
  name: python-service-xfusion
  namespace: default
  resourceVersion: "2852"
  uid: 3d71aa3c-c2cb-4b4b-9f89-cdcf5cacc245
spec:
  clusterIP: 10.96.183.9
  clusterIPs:
  - 10.96.183.9
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32345
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: python_app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}