apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"lamp"},"name":"lamp-wp","namespace":"default"},"spec":{"selector":{"matchLabels":{"app":"lamp","tier":"frontend"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"lamp","tier":"frontend"}},"spec":{"containers":[{"env":[{"name":"MYSQL_ROOT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"mysql-root-pass"}}},{"name":"MYSQL_DATABASE","valueFrom":{"secretKeyRef":{"key":"database","name":"mysql-db-url"}}},{"name":"MYSQL_USER","valueFrom":{"secretKeyRef":{"key":"username","name":"mysql-user-pass"}}},{"name":"MYSQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"mysql-user-pass"}}},{"name":"MYSQL_HOST","valueFrom":{"secretKeyRef":{"key":"host","name":"mysql-host"}}}],"image":"webdevops/php-apache:alpine-3-php7","name":"httpd-php-container","ports":[{"containerPort":80,"name":"httpd"}],"volumeMounts":[{"mountPath":"/opt/docker/etc/php/php.ini","name":"php-config-volume","subPath":"php.ini"}]},{"env":[{"name":"MYSQL_ROOT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"mysql-root-pass"}}},{"name":"MYSQL_DATABASE","valueFrom":{"secretKeyRef":{"key":"database","name":"mysql-db-url"}}},{"name":"MYSQL_USER","valueFrom":{"secretKeyRef":{"key":"username","name":"mysql-user-pass"}}},{"name":"MYSQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"mysql-user-pass"}}},{"name":"MYSQL_HOST","valueFrom":{"secretKeyRef":{"key":"host","name":"mysql-host"}}}],"image":"mysql:5.6","name":"mysql-container","ports":[{"containerPort":3306,"name":"mysql"}]}],"volumes":[{"configMap":{"name":"php-config"},"name":"php-config-volume"}]}}}}
  creationTimestamp: "2025-03-07T12:48:39Z"
  generation: 1
  labels:
    app: lamp
  name: lamp-wp
  namespace: default
  resourceVersion: "2763"
  uid: e5121f72-3bb6-495c-b9e4-e8f7016cbc09
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: lamp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lamp
        tier: frontend
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-root-pass
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: mysql-db-url
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: mysql-user-pass
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-user-pass
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: mysql-host
        image: webdevops/php-apache:alpine-3-php7
        imagePullPolicy: IfNotPresent
        name: httpd-php-container
        ports:
        - containerPort: 80
          name: httpd
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/docker/etc/php/php.ini
          name: php-config-volume
          subPath: php.ini
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-root-pass
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: mysql-db-url
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: mysql-user-pass
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-user-pass
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: mysql-host
        image: mysql:5.6
        imagePullPolicy: IfNotPresent
        name: mysql-container
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: php-config
        name: php-config-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-03-07T12:49:08Z"
    lastUpdateTime: "2025-03-07T12:49:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-03-07T12:48:39Z"
    lastUpdateTime: "2025-03-07T12:49:08Z"
    message: ReplicaSet "lamp-wp-56c7c454fc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1