apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
        listen 8097;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html index.htm index.php;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-phpfpm
  labels:
    app: nginx-phpfpm
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 8097
    volumeMounts:
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
    - name: shared-files
      mountPath: /usr/share/nginx/html
  - name: php-fpm-container
    image: php:8.3-fpm-alpine
    volumeMounts:
    - name: shared-files
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-config-volume
    configMap:
      name: nginx-config
  - name: shared-files
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-phpfpm-service
spec:
  type: NodePort
  selector:
    app: nginx-phpfpm
  ports:
  - protocol: TCP
    port: 8097
    targetPort: 8097
    nodePort: 30012